/**
 * Compliance configuration (#1180).
 *
 * Every environment variable the compliance surface reads is resolved here, so
 * "what can be configured" is one file rather than a grep.
 *
 * These keys are read through a cast rather than `getEnv().FOO` because
 * `worker-configuration.d.ts` is GENERATED by `wrangler types` from the vars and
 * secrets that happen to be present when it runs — a key that is unset in the
 * generating environment simply isn't in the `Env` interface, so the direct
 * access would fail typecheck on a fresh clone. Compliance config is optional by
 * design (an unset value means "feature off" or "use the default"), which is
 * exactly the shape that cannot be expressed against that generated type.
 * Keep the cast confined to this file.
 */

import { getEnv } from '#env';

/** Optional compliance env keys. Documented in `.env.example`. */
type ComplianceEnvKey =
  /** `disabled` | `portrait_and_restricted` | `all_generation`. */
  | 'IDENTITY_VERIFICATION_POLICY'
  /** Which adapter performs checks: `manual_review` | `byteplus_rpv` | `dev_stub`. */
  | 'IDENTITY_VERIFICATION_PROVIDER'
  /** Salt for the verified-name hash. Unset ⇒ no duplicate-identity detection. */
  | 'IDENTITY_HASH_SALT'
  /** Base URL of the provider-hosted verification flow. */
  | 'BYTEPLUS_RPV_BASE_URL'
  /** Shared secret the provider's callback must present. */
  | 'BYTEPLUS_RPV_CALLBACK_SECRET'
  /** Where abuse reports are emailed. Unset ⇒ queue-only, no notification. */
  | 'ABUSE_REPORT_NOTIFY_EMAIL';

export function complianceEnv(key: ComplianceEnvKey): string | undefined {
  // `Reflect.get` rather than a cast: the key is not on the generated `Env`
  // interface (that is the whole problem), and an assertion to a broad record
  // would claim more about the shape than we know. This reads one property and
  // narrows what comes back.
  const value: unknown = Reflect.get(getEnv(), key);
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  return trimmed ? trimmed : undefined;
}
